apiVersion: v1
kind: Service 
metadata: 
  name: myapp-service
spec:
  type: ClusterIP
  ports: 
   -  targetPort: 80
      port: 80                                       # ***REQUIRED FIELD***
  selector:                                          #Pull the labels from the deployment.yaml file which will run on the targetPort - this will link service to the Pod
    app: nginx