apiVersion: apps/v1
kind: ReplicaSet 
metadata: 
  name: myapp-replicaset
  labels: 
    app: myapp
    type: front-end
spec:
  selector: 
    matchLabels:
      type: front-end
  replicas: 3
  template:
    metadata:
      name: nginx
      labels:
        app: myapp
        type: front-end
    spec:
      containers:
       - name: nginx
         image: nginx